### ISSUE TITLE
Startup error with cx_freeze

### ISSUE THREAD

**Issue by electricmessiah** [GitExl/WhackEd4#10]
This was working fine for the past few days on Win 10 x64, but today I tried to load it and all I get is this error. I've tried a few different versions with the same result. I've also tried reinstalling fresh with the same result. It could be something on my machine, but I am at a loss for what it could be that occurred in the past 48 hours. In any case, I'm documenting it here. 

![2019-08-21 18-44-19](https://user-images.githubusercontent.com/3809405/63473543-d1030600-c443-11e9-9cc5-542426db18a9.jpg)

**Comment by GitExl** [comment]
Deleting settings.json in %appdata%/whacked4 should help with this. Sometimes it seems that the settings file get corrupted and it cannot be read anymore.

**Comment by electricmessiah** [comment]
This solved the problem.
