### ISSUE TITLE
Issue with MBF tables and above

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#11]
State 968 frame seems to have the wrong next frame.
Currently 968's next frame is 965, which must be wrong.

Also this in the mbf source code info.c ...

// killough 8/9/98: grenade
  {SPR_MISL,32768,1000,A_Die,S_GRENADE},      // S_GRENADE

  // killough 8/10/98: variable damage explosion
  {SPR_MISL,32769,4,A_Scream,S_DETONATE2},    // S_DETONATE
  {SPR_MISL,32770,6,A_Detonate,S_DETONATE3},  // S_DETONATE2
  {SPR_MISL,32771,10,NULL,S_NULL},            // S_DETONATE3

so if the mbf source is correct, the order should be 
968, frame 0 next  968
969 frame 1 next 970
970 frame 2 next 971
971 frame 3 next 0

**Comment by GitExl** [comment]
Thanks for the report, that'll be fixed in the next release.
