### ISSUE TITLE
Possible issue with Whacked 1.30 beta - MBF

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#18]
MBF states in 1.2.4 go up to State 1075, which I believe is correct, whereas with 1.3.0 beta, goes up to State 1088.

**Comment by GitExl** [comment]
It seems that I misplaced a number of states. After comparing a few source ports that implements DEHEXTRA, I've updated the 1.3.0 beta release with fixed table files. Thanks!
