### ISSUE TITLE
Doom Thing Flag Transshift

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#22]
Currently, WhackEd4 has the Doom Thing Flag UNUSED1, but according to the Doom source code,
it should be TRANSSHIFT.
https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/p_mobj.h
at line 201.
Even Greg Lewis's DeHackEd has 4 unused slots after the color 2 flag setting.
Might not be an issue, but certainly an observation.

More on this ...

Boom202 source code has this in BOOMDEH.txt ...

UNUSED1,      0x08000000 - undefined or second bit for translation
                                  Color 2 (brown/red)

Yet the Boom202 source code p_mobj.h has the same as the Doom source ...
   MF_TRANSSHIFT       = 26,

???

More on this #2 ...

https://soulsphere.org/projects/boomref/mbfedit.html#sec6 point 4

So I'm guessing Boom should use the mnemonic TRANSLATION while MBF etc. can use either TRANSLATION or TRANSLATION1.

**Comment by GitExl** [comment]
I'm a bit confused about MF_TRANSSHIFT. No thing seems to use it in the Boom source, and nothing can set it externally? It only seems to be set for thingtype 1 (player).

Issue #2 is "empty" for me, did GitHub erase it for some reason?

I've added the TRANSLATION1 flag to MBF though, aliased to TRANSLATION for compatibility.

**Comment by hawkwind3** [comment]
Not important so I closed it.
