### ISSUE TITLE
MBF minor issue

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#24]
I've noticed that whacked4-1.3.0-beta places the TRANSLUCENT Thing Flag under the Color 2 flag,
whereas whacked4 1.2.4 places this flag correctly under the Friendly flag.

**Comment by GitExl** [comment]
It seems the current beta version didn't even display the translucent flag at all. I've simplified building the list of flags so that it displays all non-aliased flags and sorts them better. Thanks!
