### ISSUE TITLE
tables_doomretro.json error 1.3.0 beta

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#25]
There is an error in tables_doomretro.json for 1.3.0 beta.

Lines 159 to 162 ...

"TRANSLUCENT": {
			"field": "retroFlags",
			"name": "Translucent"
		},

should be deleted, as this is handled by basetable_boom.json and is a bit field, not a retrobits field.

**Comment by GitExl** [comment]
Looking at the Doom Retro source (deh.c), TRANSLUCENT exists in both the Bits and Retro Bits fields. WhackEd doesn't actually support that right now though, it'll just use one of both.

**Comment by GitExl** [comment]
This was a headache, but should be fixed now. Enjoy seeing "Translucent" twice in the list of thing flags :)
