### ISSUE TITLE
Unused thing in state menu crashes WhackEd4 (MBF)

### ISSUE THREAD

**Issue by Engired** [GitExl/WhackEd4#28]
Version: 1.3
OS: Windows 10

Crash on scrolling down on filter in the states menu.
Format was MBF, clicking on 'unused' in the states menu achieves the same result.

Extra details below:
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:242: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:244: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:246: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:248: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:250: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:252: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:254: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:256: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:258: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:2423: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3667: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3669: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4077: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4079: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "C:\GitHub\WhackEd4\src\whacked4\ui\editors\statesframe.py", line 907, in filter_select
  File "C:\GitHub\WhackEd4\src\whacked4\ui\editors\statesframe.py", line 364, in filter_update
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\statequery\query.py", line 29, in execute
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\statequery\unusedfilter.py", line 30, in apply
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\statequery\filterbase.py", line 19, in expand_used_states
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\statequery\filterbase.py", line 26, in __get_states_used_by
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\table.py", line 225, in __getitem__
IndexError: list index out of range

**Comment by hawkwind3** [comment]
With the current public beta I can confirm this. Recent config updates have fixed this ( or at least it doesn't crash. ). Might be time for a new public beta Exl.  ;) .

**Comment by GitExl** [comment]
You're right on both counts. The BLD2 sprite actually belongs in the extended Dehacked config, as per https://www.doomworld.com/forum/post/2155809
