### ISSUE TITLE
Whacked4 1.30 beta 2 issues

### ISSUE THREAD

**Issue by hawkwind3** [GitExl/WhackEd4#29]
MBF and above show this twice in the Things/Flags table ...

Color2 (brown\red)

To fix, this needs to be added to basetable_mbf.json ...

"UNUSED1" : {
			"alias": "TRANSLATION2"
		},

Also for MBF and above, TRANSLUCENT is not showing in its "correct" position. Should be under Friendly.

**Comment by GitExl** [comment]
Good catch, fixed. Thanks.
