### ISSUE TITLE
WhackEd4 calls deprecated "item", advises :meth:'AddTool', plus Par Time and Booting Files

### ISSUE THREAD

**Issue by NeophyteRonin** [GitExl/WhackEd4#32]
Either I'm using an old version of Python (are there system requirements I can look at?) or I'm trying to do something it can't do, period.

While trying to boot up an existing .BEX file, it issues a warning about an inability to locate text, asks if I would like to continue and, between hitting Yes and No, it still spills this out.

This is what it reads:

C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:242: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:244: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:246: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:248: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:250: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:252: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:254: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:256: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:258: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:2423: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3667: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3669: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4077: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4079: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "C:\GitHub\WhackEd4\src\whacked4\ui\dialogs\startdialog.py", line 46, in open_file
  File "C:\GitHub\WhackEd4\src\whacked4\ui\mainwindow.py", line 166, in open_file_dialog
  File "C:\GitHub\WhackEd4\src\whacked4\ui\mainwindow.py", line 260, in open_file
  File "C:\GitHub\WhackEd4\src\whacked4\ui\mainwindow.py", line 451, in update_ui
  File "C:\GitHub\WhackEd4\src\whacked4\ui\editors\statesframe.py", line 141, in build
  File "C:\GitHub\WhackEd4\src\whacked4\ui\editors\statesframe.py", line 366, in filter_update
  File "C:\GitHub\WhackEd4\src\whacked4\ui\state_list.py", line 146, in set_state_query_result
  File "C:\GitHub\WhackEd4\src\whacked4\ui\state_list.py", line 110, in build
  File "C:\GitHub\WhackEd4\src\whacked4\ui\state_list.py", line 131, in update_row
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\patch.py", line 689, in get_state_name
IndexError: list index out of range

Also, when I press "Add" in the "Par Time" segment, I run into this one:

C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:242: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:244: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:246: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:248: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:250: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:252: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:254: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:256: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:258: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:2423: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3667: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:3669: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4077: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
C:\GitHub\WhackEd4\src\whacked4\ui\windows.py:4079: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
Traceback (most recent call last):
  File "C:\GitHub\WhackEd4\src\whacked4\ui\editors\parframe.py", line 132, in par_add
  File "C:\GitHub\WhackEd4\src\whacked4\dehacked\entry.py", line 68, in __setitem__
KeyError: 'Cannot find patch key "episode".'

So, I have python 3.10.8 (or rather, I downloaded and installed it).  If WhackEd4 uses Python for its code and the most recent one is stable, here's hoping this will change things.

Update: And, nothing changed.  It's still reading errors like crazy.

**Comment by GitExl** [comment]
The deprecation warnings you can ignore. But something in that patch is causing it to die. What version of Whacked are you using, and could you upload the patch file itself?

**Comment by NeophyteRonin** [comment]
I used v1.30Beta with the following file.  Note that it's meant to be a .DEH, but GitHub doesn't know what a .DEH is (it's otherwise a Text File).
[DEHACKED.TXT](https://github.com/GitExl/WhackEd4/files/9834458/DEHACKED.TXT)

**Comment by GitExl** [comment]
The patch loads now in current builds, thanks for the report!
