### ISSUE TITLE
Generate new json files

### ISSUE THREAD

**Issue by atsb** [GitExl/WhackEd4#34]
Say I made some modifications to the frame positions or added a few extra tables.  How would I generate a new .json file with those changes?  I've looked around but can't see exactly how someone would go about doing this.

Surely these 10,000 / 80,000 line files aren't made by hand?

**Comment by GitExl** [comment]
They were originally made from data extracted from the Doom executables, and any adjustments after that it was either manual labor (with macros and multi-cursor being a big help) or writing a script to do a thing to it.
