### ISSUE TITLE
ZDaemon: "Rocket explosion style" in "Miscellaneous" does not permit useful input.

### ISSUE THREAD

**Issue by Acts19quiz** [GitExl/WhackEd4#39]
**Version**
Up to and including 1.3.0 beta 2

**OS**
Windows 10 64-bit LTSC

**Installed Python version**
3.10.10 64-bit

**Description**
When editing Things, the valid "Render style" options are:
- None
- Normal
- Fuzzy
- Lost soul translucency
- Optional fuzzy
- Shaded
- Translucent
- Additive
- Stencil
- Translucent stencil

However, when editing the separate option for rocket explosions in "Miscellaneous", the field of "Rocket explosion style" only permits entry of an integer of 0-255, none of which are valid render styles. This should be either:

- Something akin to the On/Off booleans where clicking it will cycle through the valid options.
- A field that offers a list of drop-down options if you click on it.
- A plain string entry field, where users can input any string they want.

**Comment by GitExl** [comment]
Changed the type to "string" and set the correct default value. Thanks!.
