### ISSUE TITLE
Port to *Nix and other operating systems.

### ISSUE THREAD

**Issue by Danfun64** [GitExl/WhackEd4#7]
There doesn't seem to be that much preventing WhackEd4 from running on other operating systems, considering the WxWidget and Python base. However, it seems to rely on Win32GUI a bit too much.

Maybe port with WineLib or make it completely OS agnostic?

edit: or maybe it just looks like its incompatible with *Nix operating systems at first glance, as I see something about Mac fixes.

edit 2: At the very least, can you make it clearer that it can be compiled or run on other operating systems without Wine?

**Comment by GitExl** [comment]
While I do keep cross-platform compatibility in mind for WhackEd, the only properly tested and therefore "official" platform is still just Windows. I lack the hardware and\or knowledge for *nix\OSX development, so someone else would have to be responsible for building and verifying those versions. So far someone has managed to get an OSX version working but not without some issues. Until there is a properly working build for a platform that isn't Windows, I don't feel comfortable advertising WhackEd as cross-platform.
