### ISSUE TITLE
Sprite replacement problem

### ISSUE THREAD

**Issue by AnotherLife** [GitExl/WhackEd4#8]
http://wikisend.com/download/203908/SMOOTHED.zip

If you load my bex with doom2.wad as IWAD and the SMOOTHED.wad as PWAD, using the Doom Retro preset and go to frame 422 where an alternative death animation starts, the frames 422, 423, 424 have wrong sprites being shown.

I am using 1.1.1 beta.

**Comment by GitExl** [comment]
Thanks for the bug report! This is a known WhackEd4 bug where a sprite with rotations cannot yet be replaced by a sprite without any rotations.

I'm attaching the test file to this reply for future reference: [SMOOTHED.zip](https://github.com/GitExl/WhackEd4/files/560740/SMOOTHED.zip)

**Comment by GitExl** [comment]
This is fixed in 1.1.2.
